Repository dateutil/dateutil, pull requests merged in 2018-09, with the labels that each got.

#810 Fix bug with Samoan offset change, refactor base offset change handling
  changelog.d/810.bugfix.rst
  dateutil/test/test_tz.py
  dateutil/tz/tz.py
Labels: bug, tests, time zones

#811 Improve tzname_in_python2 decorator
  changelog.d/811.bugfix.rst
  dateutil/tz/_common.py
Labels: enhancement, time zones

#813 Always use io.BytesIO/StringIO over six; on all supported Pythons
  changelog.d/813.misc.rst
  dateutil/test/test_parser.py
  dateutil/test/test_tz.py
Labels: compat, tests

#816 Pin sphinx to <1.8.0 for docs build
  docs/requirements-docs.txt
Labels: build, documentation

#814 setup.py test doesn't work, so exit with 1
  changelog.d/814.bugfix.rst
  setup.py
Labels: bug, build, tests

#819 Change sphinx pin to != 1.8.0
  docs/requirements-docs.txt
Labels: build, documentation

#817 Remove unnecessary binary_type compatibility shim
  changelog.d/817.bugfix.rst
  dateutil/parser/_parser.py
  dateutil/test/test_isoparser.py
Labels: style

#767 Separate out input_format tests
  changelog.d/767.misc.rst
  dateutil/test/test_parser.py
Labels: parser, tests
