Repository dateutil/dateutil, pull requests merged in 2018-10, with the labels that each got.

#822 BUG: Closes #820 Accepting 'z' as valid UTC in isoparser
  changelog.d/822.bugfix.rst
  dateutil/parser/_parser.py
  dateutil/parser/isoparser.py
  dateutil/test/test_isoparser.py
  dateutil/test/test_parser.py
Labels: enhancement, isoparser

#824 Pin freezegun on Python 3.3
  requirements-dev.txt
Labels: build, tests

#825 Update tzdata to 2018f
  changelog.d/000.data.rst
  zonefile_metadata.json
Labels: time zones

#828 Update NEWS with changes for 2.7.4
  NEWS
  requirements-dev.txt
  zonefile_metadata.json
Labels: release

#774 Add solution to Martin Luther King Day exercise
  docs/exercises/index.rst
  docs/exercises/solutions/mlk-day-rrule.rst
  docs/exercises/solutions/mlk_day_rrule_solution.py
  setup.cfg
Labels: docs exercises, documentation

#831 Release 2.7.5
  NEWS
  dateutil/zoneinfo/dateutil-zoneinfo.tar.gz
  zonefile_metadata.json
Labels: release

#832 Port over 2.7.5 release
  NEWS
  changelog.d/830.data.rst
Labels: documentation
