Repository dateutil/dateutil, pull requests merged in 2018-03, with the labels that each got.

#622 isoparser strictness clarification and relaxation
  dateutil/parser/isoparser.py
  dateutil/test/test_isoparser.py
Labels: documentation, enhancement, parser

#624 Support for TZID= in rrulestr
  dateutil/rrule.py
  dateutil/test/test_rrule.py
Labels: enhancement, rrule

#626 Drop support for Python 3.2
  setup.py
  tox.ini
Labels: build, release

#628 More caching and singletons in tz
  dateutil/test/test_tz.py
  dateutil/tz/_factories.py
  dateutil/tz/tz.py
Labels: time zones

#540 Warn on unidentified tz
  dateutil/parser/__init__.py
  dateutil/parser/_parser.py
  dateutil/test/test_parser.py
Labels: enhancement, parser

#629 Update NEWS
  NEWS
Labels: documentation, release

#630 Fix license trove classifier
  setup.py
Labels: documentation

#636 Catch non-ValueError exceptions in decimal
  dateutil/parser/_parser.py
  dateutil/test/test_parser.py
Labels: parser

#634 require UTC for UNTIL when DTSTART is timezone-aware
  dateutil/rrule.py
  dateutil/test/test_rrule.py
Labels: rrule

#644 Update license and gitignore
  .gitignore
  setup.py
Labels: build, style

#643 Update tzdata to 2018d
  dateutil/test/test_tz.py
  dateutil/zoneinfo/dateutil-zoneinfo.tar.gz
  zonefile_metadata.json
Labels: time zones

#645 Add towncrier for changelog management
  CONTRIBUTING.md
  changelog.d/.gitignore
  changelog.d/template.rst
  pyproject.toml
Labels: enhancement, release

#648 Add README.rst as long_description
  changelog.d/648.misc
  setup.py
Labels: build, documentation

#649 Release 2.7.1
  NEWS
  setup.py
Labels: build, release

#655 Update readme links to pypi.org
  README.rst
  changelog.d/655.misc
Labels: documentation

#656 Release 2.7.2
  NEWS
  changelog.d/651.misc.rst
  changelog.d/655.misc
  pyproject.toml
Labels: release
