Repository dateutil/dateutil, pull requests merged in 2018-08, with the labels that each got.

#799 Pin setuptools version on Python 3.3
  .travis.yml
  changelog.d/799.misc.rst
Labels: build, tests

#798 Add test cases for positive offsets
  AUTHORS.md
  dateutil/test/test_parser.py
Labels: parser, tests

#801 Stop trying to add None to the weakref cache
  changelog.d/672.bugfix.rst
  dateutil/test/test_tz.py
  dateutil/tz/tz.py
Labels: bug, time zones
