Repository dateutil/dateutil, pull requests merged in 2018-07, with the labels that each got.

#783 Updated the Readme.rst
  AUTHORS.md
  README.rst
Labels: documentation

#785 Start testing against master branch of tz project
  .travis.yml
  changelog.d/785.misc.rst
  ci_tools/make_zonefile_metadata.py
  ci_tools/run_tz_master_env.sh
  dateutil/test/conftest.py
  tox.ini
  updatezinfo.py
Labels: build, tests

#791 Use Python3.7's nullcontext if available
  changelog.d/791.misc.rst
  dateutil/tz/tz.py
Labels: style, time zones
