Repository dateutil/dateutil, pull requests merged in 2018-04, with the labels that each got.

#672 Updates Tz Singletons and Caches with `WeakValueDictionary`s
  AUTHORS.md
  changelog.d/672.bugfix.rst
  dateutil/test/test_tz.py
  dateutil/tz/_factories.py
  dateutil/tz/tz.py
Labels: enhancement, time zones

#680 Add pull request template
  .github/pull_request_template.md
Labels: enhancement, style

#674 Hypothesis tests on convertyear
  .gitignore
  AUTHORS.md
  changelog.d/674.misc.rst
  dateutil/parser/_parser.py
  dateutil/test/property/test_parser_prop.py
  requirements-dev.txt
Labels: parser, tests

#689 Change over badge pypi links
  README.rst
Labels: documentation

#690 Update version added documentation
  .gitignore
  dateutil/parser/isoparser.py
  dateutil/utils.py
Labels: documentation, isoparser, utils

#688 Add hypothesis tests for isoparse
  changelog.d/688.misc.rst
  dateutil/test/property/test_isoparse_prop.py
Labels: isoparser, tests

#696 Add linkcheck options
  README.rst
  docs/conf.py
Labels: documentation, enhancement

#695 change the order of cache and byeaster in rrule docstring
  AUTHORS.md
  changelog.d/695.doc.rst
  dateutil/rrule.py
Labels: documentation

#699 Add test for repr of named fileobject in tzfile
  AUTHORS.md
  changelog.d/699.misc.rst
  dateutil/test/test_tz.py
Labels: tests, time zones

#706 Cleanup tz docs and PEP8
  changelog.d/706.doc.rst
  dateutil/tz/tz.py
Labels: documentation, style

#707 Add changelog to documentation
  NEWS
  changelog.d/692.doc.rst
  changelog.d/707.doc.rst
  docs/changelog.rst
  docs/conf.py
  docs/index.rst
  docs/requirements-docs.txt
  tox.ini
Labels: documentation

#671 Added examples to tzfile docstring
  changelog.d/671.doc.rst
  dateutil/tz/tz.py
Labels: documentation
