Repository dateutil/dateutil, pull requests merged in 2018-05, with the labels that each got.

#710 Update zonefile to 2018e
  changelog.d/710.data.rst
  dateutil/zoneinfo/dateutil-zoneinfo.tar.gz
  zonefile_metadata.json
Labels: time zones

#711 Fix links to ISO year week number notation
  changelog.d/670.doc.rst
  docs/examples.rst
  docs/relativedelta.rst
Labels: documentation

#700 Fix for B.Y.d format corner case #687
  changelog.d/687.bugfix.rst
  dateutil/parser/_parser.py
  dateutil/test/test_parser.py
Labels: bug, parser

#704 gettz documentation
  AUTHORS.md
  changelog.d/704.doc.rst
  dateutil/tz/tz.py
  docs/tz.rst
Labels: documentation

#714 Restructure tz docs
  changelog.d/714.doc.rst
  dateutil/tz/__init__.py
  dateutil/tz/tz.py
  docs/tz.rst
Labels: documentation, time zones

#716 Revert weakref
  AUTHORS.md
  changelog.d/672.bugfix.rst
  dateutil/test/test_tz.py
  dateutil/tz/_factories.py
  dateutil/tz/tz.py
Labels: time zones

#721 Comma separator for ISO 8601 parser
  changelog.d/721.bugfix.rst
  dateutil/parser/isoparser.py
  dateutil/test/test_isoparser.py
Labels: bug, isoparser

#723 Fix Python 3.3 tests, make setup.py PEP 8 compliant
  .travis.yml
  changelog.d/723.misc.rst
  setup.py
Labels: build, style
