Repository dateutil/dateutil, pull requests merged in 2019-11, with the labels that each got.

#969 Remove WarningTestMixin in favor of pytest.warns
  changelog.d/969.misc.rst
  dateutil/test/_common.py
  dateutil/test/test_relativedelta.py
  dateutil/test/test_rrule.py
  dateutil/test/test_tz.py
Labels: tests

#935 Fix error message for gettz when passed bytes
  AUTHORS.md
  changelog.d/935.misc.rst
  dateutil/test/test_tz.py
  dateutil/tz/tz.py
Labels: enhancement

#970 Add Python 3.8 to trove classifiers and Travis.
  .travis.yml
  README.rst
  changelog.d/970.misc.rst
  setup.cfg
Labels: build

#928 Fix test_tzlocal_offset_equal[GMT-tzoff1]
  changelog.d/928.bugfix.rst
  dateutil/test/test_tz.py
Labels: bug, tests

#973 Lock around strong cache updates
  changelog.d/973.bugfix.rst
  dateutil/tz/_factories.py
Labels: bug, time zones

#971 Updates to the release process
  .travis.yml
  RELEASING
  changelog.d/971.misc.rst
  changelog.d/template.rst
  pyproject.toml
  tox.ini
Labels: build

#974 Prepare 2.8.1 release
  NEWS
  changelog.d/735.misc.rst
  changelog.d/871.misc.rst
  changelog.d/875.misc.rst
  changelog.d/876.misc.rst
  changelog.d/879.misc.rst
  changelog.d/881.bugfix.rst
  changelog.d/882.misc.rst
  changelog.d/890.misc.rst
  changelog.d/891.bugfix.rst
  changelog.d/891.misc.rst
  changelog.d/892.misc.rst
  changelog.d/893.misc.rst
  changelog.d/894.misc.rst
  changelog.d/910.bugfix.rst
  changelog.d/915.misc.rst
  changelog.d/916.misc.rst
  changelog.d/928.bugfix.rst
  changelog.d/934.misc.rst
  changelog.d/935.misc.rst
  changelog.d/950.bugfix.rst
  changelog.d/952.misc.rst
  changelog.d/961.data.rst
  changelog.d/962.misc.rst
  changelog.d/963.bugfix.rst
  changelog.d/966.misc.rst
  changelog.d/969.misc.rst
  changelog.d/970.misc.rst
  changelog.d/971.misc.rst
  changelog.d/973.bugfix.rst
Labels: release

#982 Drop Python 3.3 on Appveyor
  appveyor.yml
  changelog.d/982.misc.rst
Labels: build
