Repository dateutil/dateutil, pull requests merged in 2019-02, with the labels that each got.

#861 Catch UnicodeEncodeError for Windows in tz.gettz
  changelog.d/861.bugfix.rst
  dateutil/test/test_tz.py
  dateutil/tz/tz.py
Labels: bug, time zones

#859 Add parameters parsing to EXDATE
  AUTHORS.md
  changelog.d/410.feature.rst
  dateutil/rrule.py
  dateutil/test/test_rrule.py
Labels: enhancement, rrule

#863 Add build backend to pyproject.toml
  MANIFEST.in
  changelog.d/863.bugfix.rst
  pyproject.toml
Labels: build

#865 Fix changelog
  NEWS
Labels: documentation, release

#868 add Azure Pipelines
  azure-pipelines.yml
  ci_tools/run_tz_master_env.sh
  tox.ini
Labels: build

#875 add fix for 2019hackIllinois Use pep517.build in release.py #869
  AUTHORS.md
  changelog.d/875.misc.rst
  release.py
  requirements-dev.txt
  setup.cfg
Labels: build

#877 add Azure Pipelines badge
  README.rst
Labels: build
