Repository dateutil/dateutil, pull requests merged in 2019-04, with the labels that each got.

#909 Pin tox to 3.8.0 in CI
  .travis.yml
  azure-pipelines.yml
Labels: tests

#907 Update tzdata to 2019a
  changelog.d/907.data.rst
  dateutil/zoneinfo/dateutil-zoneinfo.tar.gz
  zonefile_metadata.json
Labels: time zones

#913 add PyPy versions on Windows
  AUTHORS.md
  azure-pipelines.yml
Labels: build
