Repository dateutil/dateutil, pull requests merged in 2020-04, with the labels that each got.

#1020 Migrate PyPy CI to GitHub Actions
  .github/workflows/test_pypy.yml
  .travis.yml
  changelog.d/1020.misc.rst
  tox.ini
Labels: build

#1025 Document methods in `rrule` module
  changelog.d/1025.doc.rst
  dateutil/rrule.py
  docs/rrule.rst
Labels: documentation

#1034 Update zoneinfo to 2020a
  changelog.d/1034.data.rst
  dateutil/zoneinfo/dateutil-zoneinfo.tar.gz
  zonefile_metadata.json
Labels: time zones

#986 Fix simple typo: negilible -> negligible
  AUTHORS.md
  changelog.d/985.doc.rst
  dateutil/utils.py
Labels: documentation, utils

#1024 Fix tz.gettz() not returning local time for empty string
  changelog.d/1024.misc.rst
  dateutil/test/property/test_tz_prop.py
  dateutil/test/test_tz.py
  dateutil/tz/tz.py
Labels: bug, time zones
